# Generated by Django 5.2.6 on 2025-09-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices_app', '0003_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Cidade', 'verbose_name_plural': 'Cidades'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfis'},
        ),
        migrations.AlterModelOptions(
            name='response',
            options={'verbose_name': 'Resposta', 'verbose_name_plural': 'Respostas'},
        ),
        migrations.AlterModelOptions(
            name='servicecatogarys',
            options={'verbose_name': 'Categoria de Serviço', 'verbose_name_plural': 'Categorias de Serviços'},
        ),
        migrations.AlterModelOptions(
            name='servicerequests',
            options={'verbose_name': 'Solicitação de Serviço', 'verbose_name_plural': 'Solicitações de Serviços'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterModelOptions(
            name='workers',
            options={'verbose_name': 'Trabalhador', 'verbose_name_plural': 'Trabalhadores'},
        ),
    ]
